//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourGuide.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartTourGuide.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string AlertInfo {
            get {
                return ResourceManager.GetString("AlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔙 Quay lại.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Ngôn ngữ.
        /// </summary>
        public static string BtnLanguage {
            get {
                return ResourceManager.GetString("BtnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔊 Nghe Thuyết Minh.
        /// </summary>
        public static string BtnListen {
            get {
                return ResourceManager.GetString("BtnListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Vị trí.
        /// </summary>
        public static string BtnMyLocation {
            get {
                return ResourceManager.GetString("BtnMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗣️ Đọc Tự Động (TTS).
        /// </summary>
        public static string BtnReadTts {
            get {
                return ResourceManager.GetString("BtnReadTts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại điểm đến.
        /// </summary>
        public static string BtnReload {
            get {
                return ResourceManager.GetString("BtnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Chọn Tour.
        /// </summary>
        public static string BtnSelectTour {
            get {
                return ResourceManager.GetString("BtnSelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹️ Dừng phát.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến máy chủ. Vui lòng kiểm tra mạng hoặc địa chỉ API..
        /// </summary>
        public static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ du lịch.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có mô tả..
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại chưa có tour nào được cập nhật..
        /// </summary>
        public static string NoToursAvailable {
            get {
                return ResourceManager.GetString("NoToursAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gồm {0} địa điểm.
        /// </summary>
        public static string PoiCountFormat {
            get {
                return ResourceManager.GetString("PoiCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử lại.
        /// </summary>
        public static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hành trình của bạn.
        /// </summary>
        public static string SelectTourHeader {
            get {
                return ResourceManager.GetString("SelectTourHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: {0}.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tìm bạn....
        /// </summary>
        public static string StatusFindingLocation {
            get {
                return ResourceManager.GetString("StatusFindingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tìm thấy vị trí của bạn!.
        /// </summary>
        public static string StatusFound {
            get {
                return ResourceManager.GetString("StatusFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi GPS. Hãy bật vị trí!.
        /// </summary>
        public static string StatusGpsError {
            get {
                return ResourceManager.GetString("StatusGpsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đổi ngôn ngữ .
        /// </summary>
        public static string StatusLanguageChanged {
            get {
                return ResourceManager.GetString("StatusLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tải {0} địa điểm..
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải dữ liệu....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi: {0}.
        /// </summary>
        public static string SystemErrorMessage {
            get {
                return ResourceManager.GetString("SystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyến Du Lịch.
        /// </summary>
        public static string ToursPageTitle {
            get {
                return ResourceManager.GetString("ToursPageTitle", resourceCulture);
            }
        }
    }
}
