// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartTourGuide.API.Data;

#nullable disable

namespace SmartTourGuide.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407123000_RemoveUserIdFromUserLocationLogs")]
    partial class RemoveUserIdFromUserLocationLogs
    {
    }
}